##############################################################################
# GitHub Actions Workflow for Easy3D to build tests with GCC
#
# Copyright (C) 2022 Liangliang Nan <liangliang.nan@gmail.com>
# Copyright (c) 2021 Vissarion Fisikopoulos
#
# Licensed under GNU LGPL.3, see LICENCE file
##############################################################################
name: cmake-gcc

on: [push, pull_request]

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
          fail-fast: false
          matrix:
            platform: [windows, ubuntu, macos]
            build_type: [Debug, Release]
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v1
      - if: ${{ matrix.platform == 'ubuntu' }}
        name: Set up
        run: sudo apt-get update || true;
             sudo apt-get install libgl1-mesa-dev mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev;
      - name: Configure
        run: cmake -H"." -B"build/${{ matrix.platform }}" -DEasy3D_BUILD_TESTS=ON;
      - name: "${{ matrix.platform }} - ${{ matrix.build_type }}"
        run: cmake --build "build/${{ matrix.platform }}";